// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import ()

type Tsarka struct {
	ID           int32  `json:"id"`
	String       string `json:"string"`
	MaxSubstring string `json:"max_substring"`
}
